Add minor performance enhancements
Signed-off-by: Dani Llewellyn <diddledani@ubuntu.com>

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -1,5 +1,8 @@
 name: fakecam
 adopt-info: fakecam
+# issues: https://github.com/diddlesnaps/fakecam/issues
+# source-code: https://github.com/diddlesnaps/fakecam.git
+# donation: https://liberapay.com/diddledani
 summary: Fakecam
 description: |
   Fake background removing camera for streaming and video
@@ -7,7 +10,7 @@ description: |
 
   https://elder.dev/posts/open-source-virtual-background/
 
-base: core18
+base: core20
 grade: stable
 confinement: strict
 compression: lzo
@@ -17,31 +20,34 @@ architectures:
   - build-on: arm64
   - build-on: armhf
 
-# package-repositories:
-#   - type: apt
-#     formats: [deb]
-#     components: [main]
-#     suites: [all]
-#     key-id: 52ABD6E87E421793971873FFACFA9FC57E6C5DBE
-#     url: https://apt.repos.intel.com/openvino/2021
-#   - type: apt
-#     formats: [deb]
-#     path: /
-#     key-id: AE09FE4BBD223A84B2CCFCE3F60F4B3D7FA2AF80
-#     url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64
-#   - type: apt
-#     formats: [deb]
-#     path: /
-#     key-id: AE09FE4BBD223A84B2CCFCE3F60F4B3D7FA2AF80
-#     url: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64
+package-repositories:
+  - type: apt
+    formats: [deb]
+    components: [main]
+    suites: [all]
+    key-id: 52ABD6E87E421793971873FFACFA9FC57E6C5DBE
+    url: https://apt.repos.intel.com/openvino/2021
+  - type: apt
+    formats: [deb]
+    path: /
+    key-id: AE09FE4BBD223A84B2CCFCE3F60F4B3D7FA2AF80
+    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64
+  - type: apt
+    formats: [deb]
+    path: /
+    key-id: AE09FE4BBD223A84B2CCFCE3F60F4B3D7FA2AF80
+    url: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64
 
 parts:
   snapcraft-preload:
     source: https://github.com/sergiusens/snapcraft-preload.git
     plugin: cmake
-    configflags:
+    cmake-parameters:
       - -DCMAKE_INSTALL_PREFIX=/
       - -DCMAKE_BUILD_TYPE=Release
+    build-environment:
+      - CFLAGS: -O2 -pipe
+      - CXXFLAGS: -O2 -pipe
     build-packages:
       - on amd64:
         - gcc-multilib
@@ -63,17 +69,17 @@ parts:
     source: https://github.com/opencv/opencv.git
     source-tag: '4.5.2'
     plugin: cmake
-    # build-environment:
-    #   - INTEL_OPENVINO_DIR: /opt/intel/openvino_2021.2.200
-    #   - INTEL_CVSDK_DIR: /opt/intel/openvino_2021.2.200
-    #   - InferenceEngine_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/share
-    #   - ARCH_ROOT_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/lib/intel64/arch_descriptions
-    #   - HDDL_INSTALL_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/hddl
-    #   - KMB_INSTALL_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/hddl_unite
-    #   - TBB_INSTALL_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/tbb
-    #   - ngraph_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/ngraph/cmake
-    #   - LD_LIBRARY_PATH: /opt/intel/openvino_2021.2.200/deployment_tools/ngraph/lib:/opt/intel/opencl:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/lib/intel64
-    configflags:
+    build-environment:
+      - INTEL_OPENVINO_DIR: /opt/intel/openvino_2021.2.200
+      - INTEL_CVSDK_DIR: /opt/intel/openvino_2021.2.200
+      - InferenceEngine_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/share
+      - ARCH_ROOT_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/lib/intel64/arch_descriptions
+      - HDDL_INSTALL_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/hddl
+      - KMB_INSTALL_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/hddl_unite
+      - TBB_INSTALL_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/tbb
+      - ngraph_DIR: /opt/intel/openvino_2021.2.200/deployment_tools/ngraph/cmake
+      - LD_LIBRARY_PATH: /opt/intel/openvino_2021.2.200/deployment_tools/ngraph/lib:/opt/intel/opencl:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/lib/intel64
+    cmake-parameters:
       - -DCMAKE_INSTALL_PREFIX=/usr
       - -DCMAKE_BUILD_TYPE=Release
       - -DOPENCV_EXTRA_MODULES_PATH=$SNAPCRAFT_STAGE/opencv_contrib/modules
@@ -147,11 +153,11 @@ parts:
       - -DWITH_GSTREAMER=ON
       - -DWITH_OPENGL=ON
       - -DWITH_VULKAN=ON
-      # - -DWITH_CUDA=ON
-      # - -DCUDA_HOST_COMPILER=/usr/bin/gcc-6
-      # - '"-DCUDA_ARCH_BIN=5.0"'
-      # - '"-DCUDA_ARCH_PTX=3.5"'
-      # - -DOPENCV_DNN_CUDA=ON
+      - -DWITH_CUDA=ON
+      - -DCUDA_HOST_COMPILER=/usr/bin/gcc-7
+      - -DCUDA_ARCH_BIN='5.0'
+      - -DCUDA_ARCH_PTX='5.0 6.0 7.0 7.5 8.0'
+      - -DOPENCV_DNN_CUDA=ON
       - -DOPENCV_DNN_OPENCL=ON
       - -DENABLE_FAST_MATH=1
       - -DCUDA_FAST_MATH=1
@@ -175,32 +181,33 @@ parts:
     build-snaps:
       - cmake
     build-packages:
-      # - on amd64:
-      #   - cuda-11-0
-      #   - libcudnn8-dev
+      - on amd64:
+        - cuda-11-6
+        - libcudnn8-dev
       - g++-7
       - gcc-7
       - gfortran
-      # - intel-openvino-eula-2021.2.200
-      # - intel-openvino-setupvars-2021.2.200
-      # # - intel-openvino-docs-2021.2.200
-      # - intel-openvino-ie-sdk-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-2021.2.200
-      # - intel-openvino-ie-rt-core-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-cpu-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-gpu-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-gna-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-vpu-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-hddl-ubuntu-bionic-2021.2.200
-      # # - intel-openvino-opencv-lib-ubuntu-bionic-2021.2.200
-      # # - intel-openvino-opencv-generic-2021.2.200
-      # - intel-openvino-gstreamer-rt-ubuntu-bionic-2021.2.200
-      # - intel-openvino-gva-rt-ubuntu-bionic-2021.2.200
+      - intel-openvino-eula-2021.2.200
+      - intel-openvino-setupvars-2021.2.200
+      # - intel-openvino-docs-2021.2.200
+      - intel-openvino-ie-sdk-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-2021.2.200
+      - intel-openvino-ie-rt-core-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-cpu-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-gpu-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-gna-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-vpu-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-hddl-ubuntu-focal-2021.2.200
+      # - intel-openvino-opencv-lib-ubuntu-focal-2021.2.200
+      # - intel-openvino-opencv-generic-2021.2.200
+      - intel-openvino-gstreamer-rt-ubuntu-focal-2021.2.200
+      - intel-openvino-gva-rt-ubuntu-focal-2021.2.200
       - libatlas-base-dev
       - libavcodec-dev
       - libavformat-dev
       - libavresample-dev
       - libblas-dev
+      - libboost-dev
       - libdc1394-22-dev
       - libeigen3-dev
       - libgflags-dev
@@ -213,74 +220,76 @@ parts:
       - liblapack-dev
       - libopenblas-dev
       - libopenexr-dev
-      - libopenjp2-7-dev
-      - libopenjp2-tools
-      - libopenjpip-dec-server
-      - libopenjpip-server
       - libpng-dev
       - libprotobuf-dev
       - libswscale-dev
       - libtbb-dev
-      - libtiff-dev
       - libv4l-dev
       - libva-dev
       - libvulkan-dev
-      - libwebp-dev
       - linux-libc-dev
       - ocl-icd-opencl-dev
+      - opencl-c-headers
       - python3-dev
       - python3-numpy
     stage-packages:
-      # - on amd64:
-      #   - cuda-runtime-11-0
-      #   - libcudnn8
-      # - intel-openvino-eula-2021.2.200
-      # - intel-openvino-setupvars-2021.2.200
-      # # - intel-openvino-docs-2021.2.200
-      # # - intel-openvino-ie-sdk-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-2021.2.200
-      # - intel-openvino-ie-rt-core-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-cpu-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-gpu-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-gna-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-vpu-ubuntu-bionic-2021.2.200
-      # - intel-openvino-ie-rt-hddl-ubuntu-bionic-2021.2.200
-      # # - intel-openvino-opencv-lib-ubuntu-bionic-2021.2.200
-      # # - intel-openvino-opencv-generic-2021.2.200
-      # - intel-openvino-gstreamer-rt-ubuntu-bionic-2021.2.200
-      # - intel-openvino-gva-rt-ubuntu-bionic-2021.2.200
-      # - libaccinj64-9.1
+      - on amd64:
+        - cuda-libraries-11-6
+        - libcudnn8
+      - ibverbs-providers
+      - intel-openvino-eula-2021.2.200
+      - intel-openvino-setupvars-2021.2.200
+      # - intel-openvino-docs-2021.2.200
+      # - intel-openvino-ie-sdk-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-2021.2.200
+      - intel-openvino-ie-rt-core-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-cpu-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-gpu-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-gna-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-vpu-ubuntu-focal-2021.2.200
+      - intel-openvino-ie-rt-hddl-ubuntu-focal-2021.2.200
+      # - intel-openvino-opencv-lib-ubuntu-focal-2021.2.200
+      # - intel-openvino-opencv-generic-2021.2.200
+      - intel-openvino-gstreamer-rt-ubuntu-focal-2021.2.200
+      - intel-openvino-gva-rt-ubuntu-focal-2021.2.200
+      - libaccinj64-10.1
       - libatlas3-base
-      - libavcodec57
-      - libavformat57
-      - libavresample3
+      - libavcodec58
+      - libavformat58
+      - libavresample4
       - libblas3
+      - libboost-filesystem1.71.0
+      - libboost-program-options1.71.0
       - libdc1394-22
+      - librdmacm1
       - libgflags2.2
       - libglu1-mesa
       - libgoogle-glog0v5
+      - libgstreamer-plugins-bad1.0-0
       - libgstreamer-plugins-base1.0-0
       - libgstreamer1.0-0
-      - libjpeg-turbo8
+      - libibverbs1
+      - libjpeg8
       - liblapack3
       - libopenblas-base
-      - libopenexr22
-      - libopenjp2-7
-      - libopenjpip7
+      - libopenexr24
       - libpng16-16
-      - libprotobuf10
-      - libswscale4
+      - libprotobuf17
+      - libswscale5
       - libtbb2
-      - libtiff5
+      - libtinfo5
       - libv4l-0
       - libva2
+      - libva-wayland2
       - libvulkan1
-      - libwebp6
+      - python3
+      - python3-numpy
       - mesa-opencl-icd
       - mesa-vulkan-drivers
       - va-driver-all
-    # stage:
-    #   - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcudnn*_train.so*
+      - try:
+        - libblas64-3
+        - liblapack64-3
 
   fakecam:
     after: [opencv]
@@ -326,7 +335,9 @@ parts:
       - libxext6
       - libxkbcommon-x11-0
       - libxrender1
+      - python3
       - python3-gi
+      - python3-pip
 
   other-progs:
     plugin: nil
@@ -360,37 +371,43 @@ parts:
         export VK_ICD_FILENAMES="/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon.aarch64.json"
       fi
 
+      # export PYTHONPATH=$SNAP/usr/lib/python3.8:$SNAP/lib/python3.8
+      export LD_LIBRARY_PATH=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/usr/lib:/lib/$SNAPCRAFT_ARCH_TRIPLET:/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$SNAP/cuda-11.2/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/cuda-11.2/local/cuda-11.2/lib64
       exec "$@"
-      # env LD_LIBRARY_PATH=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/usr/lib:/lib/$SNAPCRAFT_ARCH_TRIPLET:/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$SNAP/cuda-11.2/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/cuda-11.2/local/cuda-11.2/lib64 "$@"
       EOF
     override-build: |
       install -m755 -D -t $SNAPCRAFT_PART_INSTALL/bin fclaunch
 
-  cleanup:
-    after: [fakecam, other-progs]
+  # cleanup:
+  #   after: [fakecam, other-progs]
+  #   plugin: nil
+  #   build-snaps: [gnome-3-38-2004, gtk-common-themes]
+  #   override-prime: |
+  #     set -eux
+  #     
+  #     for snap in "gnome-3-38-2004" "gtk-common-themes"; do
+  #       cd "/snap/$snap/current"
+  #       [ -d "lib" ] && find ./lib -type f,l -exec rm -f "$SNAPCRAFT_PRIME/lib/{}" "$SNAPCRAFT_PRIME/usr/lib/{}" \;
+  #       [ -d "share" ] && find ./share -type f,l -exec rm -f "$SNAPCRAFT_PRIME/share/{}" "$SNAPCRAFT_PRIME/usr/share/{}" \;
+  #       [ -d "usr/lib" ] && find ./usr/lib -type f,l -exec rm -f "$SNAPCRAFT_PRIME/lib/{}" "$SNAPCRAFT_PRIME/usr/lib/{}" \;
+  #       [ -d "usr/share" ] && find ./usr/share -type f,l -exec rm -f "$SNAPCRAFT_PRIME/share/{}" "$SNAPCRAFT_PRIME/usr/share/{}" \;
+  #     done
+  #     
+  #     for CRUFT in bug lintian man; do
+  #       rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
+  #     done
+  #     
+  #     find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
+  #     find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
+
+  precompile:
+    # after: [fakecam, opencv, cleanup]
+    after: [fakecam, opencv]
     plugin: nil
-    build-snaps: [gnome-3-28-1804, gtk-common-themes] #, cuda-runtime-11-2-1804]
     override-prime: |
-      set -eux
-
-      for snap in "gnome-3-28-1804" "gtk-common-themes" # "cuda-runtime-11-2-1804"
-      do
-        cd "/snap/$snap/current"
-        [ -d "lib" ] && find ./lib -type f,l -exec rm -f "$SNAPCRAFT_PRIME/lib/{}" "$SNAPCRAFT_PRIME/usr/lib/{}" \;
-        [ -d "share" ] && find ./share -type f,l -exec rm -f "$SNAPCRAFT_PRIME/share/{}" "$SNAPCRAFT_PRIME/usr/share/{}" \;
-        [ -d "usr/lib" ] && find ./usr/lib -type f,l -exec rm -f "$SNAPCRAFT_PRIME/lib/{}" "$SNAPCRAFT_PRIME/usr/lib/{}" \;
-        [ -d "usr/share" ] && find ./usr/share -type f,l -exec rm -f "$SNAPCRAFT_PRIME/share/{}" "$SNAPCRAFT_PRIME/usr/share/{}" \;
-      done
-
-      for CRUFT in bug lintian man
-      do
-        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
-      done
-
-      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
-      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
-      rm -rf $SNAPCRAFT_PRIME/usr/share/perl
-      rm -rf $SNAPCRAFT_PRIME/usr/share/backgrounds
+      python3 -m compileall -q -j$SNAPCRAFT_PARALLEL_BUILD_COUNT $SNAPCRAFT_PRIME/lib/python3.8
+      python3 -m compileall -q -j$SNAPCRAFT_PARALLEL_BUILD_COUNT $SNAPCRAFT_PRIME/usr/lib/python3
+      python3 -m compileall -q -j$SNAPCRAFT_PARALLEL_BUILD_COUNT $SNAPCRAFT_PRIME/usr/lib/python3.8
 
 layout:
   /etc/OpenCL:
@@ -401,19 +418,8 @@ layout:
     bind: $SNAP/usr/lib/clc
   /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe:
     bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gallium-pipe
-  /usr/share/libdrm/amdgpu.ids:
-    bind-file: $SNAP/usr/share/libdrm/amdgpu.ids
   /opt/intel:
     bind: $SNAP/opt/intel
-
-# environment:
-  # /opt/intel/openvino_2021.2.200/deployment_tools/ngraph/lib:
-  # /opt/intel/opencl:
-  # /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/hddl/lib:
-  # /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/gna/lib:
-  # /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/mkltiny_lnx/lib:
-  # /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/external/tbb/lib:
-  # /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/lib/intel64
 
 # plugs:
 #   cuda-runtime-11-2-1804:
@@ -424,7 +430,7 @@ layout:
 apps:
   clinfo:
     command: usr/bin/clinfo
-    extensions: [gnome-3-28]
+    extensions: [gnome-3-38]
     plugs:
       - camera
       - desktop
@@ -438,9 +444,7 @@ apps:
 
   fakecam:
     command: bin/fclaunch $SNAP/bin/fakecamcli
-    command-chain:
-      - bin/snapcraft-preload
-    extensions: [gnome-3-28]
+    extensions: [gnome-3-38]
     plugs:
       - camera
       - desktop
@@ -456,7 +460,7 @@ apps:
     command: bin/fclaunch $SNAP/bin/fakecamgui
     command-chain:
       - bin/snapcraft-preload
-    extensions: [gnome-3-28]
+    extensions: [gnome-3-38]
     plugs:
       - camera
       - desktop
